# Site settings
title: DjangoCon Europe 2018
email: 2018@djangocon.eu
description: >
  DjangoConEurope is hosted in Heidelberg May 23-27th, 2018
baseurl: ""
url: ""
permalink: /news/:title/
twitter_username: DjangoConEurope
excerpt_separator: "<!-- more -->"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

navigation:
  - title: News
    url: /news
  - title: Timeline
    url: /timeline
  - title: Information
    url: /info
    subpages:
      - title: Getting here
        url: /info/travelling
      - title: Getting around
        url: /info/heidelberg
      - title: Accomodation
        url: /info/accomodation
      - title: Venues
        url: /info/venues
  - title: Tickets
    url: /tickets
  - title: Code of Conduct
    url: /conduct
  - title: Accessibility
    url: /access
  - title: Sponsoring
    url: /sponsoring
  - title: Contact
    url: /contact

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
